### ISSUE TITLE
Possibly add a tag or branch with stable/working code so its easier to use in rust projects

### ISSUE THREAD

**Issue by MCorange99** [chanmix51/soft65c02#6]
Im currently not seeing a way to do something like this:
```toml
...

[dependencies]
soft65c02 = {git = "https://github.com/chanmix51/soft65c02", commit = "e7e6615"}
```

so it would be nice if there was a tag or a branch that would point to `e7e6615`

Unless the library works again ofc, then i could just use `master`
